printWidth    = 80
tabWidth      = 4
useTabs       = false
singleQuote   = true
trailingComma = "none"
proseWrap     = "always"
endOfLine     = "lf"

[[overrides]]
files   = "*.yaml"
options = { tabWidth = 2, singleQuote = false }

[[overrides]]
files   = "*.json"
options = { singleQuote = false }
