name: Lint Dev

on:
  push:
    branches:
      - dev

jobs:
  clippy:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo*') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  taplo:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo*') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Taplo
        id: cache-taplo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/taplo*
          key: ${{ runner.os }}-taplo-${{ hashFiles('.taplo*') }}
          restore-keys: |
            ${{ runner.os }}-taplo-

      - name: Install Taplo
        if: ${{ steps.cache-taplo.outputs.cache-hit != 'true' }}
        run: cargo install taplo-cli

      - name: Run Taplo
        run: taplo format --check

  prettier:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Prettier
        id: cache-prettier
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules/
          key: ${{ runner.os }}-prettier-${{ hashFiles('.prettierrc*') }}
          restore-keys: |
            ${{ runner.os }}-prettier-

      - name: Install Prettier
        if: ${{ steps.cache-prettier.outputs.cache-hit != 'true' }}
        run: npm install --save-dev prettier

      - name: Run Prettier
        run: npx prettier --check "./**/*.{json,yaml}"

  markdownlint:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Markdownlint
        id: cache-markdownlint
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules/
          key: ${{ runner.os }}-markdownlint-${{ hashFiles('.markdownlint*') }}
          restore-keys: |
            ${{ runner.os }}-markdownlint-

      - name: Install Markdownlint
        if: ${{ steps.cache-markdownlint.outputs.cache-hit != 'true' }}
        run: npm install --save-dev markdownlint-cli

      - name: Run Markdownlint
        run: npx markdownlint "./**/*.md"
