name: Publish Release

on:
  workflow_run:
    workflows: ["Test Prod"]
    types:
      - completed
    branches:
      - prod

jobs:
  tag_and_publish:
    if:
      ${{ github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'prod' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Extract Version from Cargo.toml
        run: |
          version=$(grep ^version Cargo.toml | sed -E 's/version *= *"([^"]+)"/\1/')
          echo "version=$version" >> $GITHUB_ENV

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
          git fetch --all --tags

      - name: Tag Prod
        run: |
          git checkout prod
          git tag ${{ env.version }}
          git push --tags

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
